# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-01 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190731_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_html',
            field=models.TextField(blank=True, editable=False, verbose_name='正文Html代码'),
        ),
    ]
