# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-12-09 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190917_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', stdimage.models.StdImageField(blank=True, upload_to=stdimage.utils.UploadToUUID(path='images'), verbose_name='图片')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='course',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Course'),
        ),
    ]
